num1=int(input("enter num1:\t"))
num2=int(input("enter num2:\t"))
print("add",num1+num2)
print("subtract",num1*num2)
print("divide",num1/num2)
print("remainder",num1%num2)
print("quotient",num1//num2)
print("power",num1**num2)